export const CROPS = [
  {
    id: '1',
    name: 'Basmati Rice',
    farmer: 'Rajesh Kumar',
    farmerId: 'f001',
    phone: '+919848012345',
    upiId: 'rajesh.kumar@oksbi',
    location: 'Karimnagar, Telangana',
    state: 'Telangana',
    price: 42,
    unit: 'kg',
    quantity: 5000,
    qualityGrade: 'A+',
    harvestDate: '2026-09-15',
    images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop'],
    organic: true,
    verified: true,
    rating: 4.8,
    reviews: 23,
    description: 'Premium quality basmati rice, naturally grown with traditional methods. Long-grain, aromatic, excellent for export.',
    category: 'Grains',
  },
  {
    id: '2',
    name: 'Tomatoes',
    farmer: 'Suresh Patil',
    farmerId: 'f002',
    phone: '+919822054321',
    upiId: 'suresh.patil@okhdfcbank',
    location: 'Nashik, Maharashtra',
    state: 'Maharashtra',
    price: 18,
    unit: 'kg',
    quantity: 2000,
    qualityGrade: 'A',
    harvestDate: '2026-08-25',
    images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&auto=format&fit=crop'],
    organic: false,
    verified: true,
    rating: 4.5,
    reviews: 41,
    description: 'Fresh red tomatoes, ideal for bulk processing or retail. Firm texture, high yield.',
    category: 'Vegetables',
  },
  {
    id: '3',
    name: 'Cotton',
    farmer: 'Venkatesh Reddy',
    farmerId: 'f003',
    phone: '+919440198765',
    upiId: 'venkatesh.reddy@icici',
    location: 'Guntur, Andhra Pradesh',
    state: 'Andhra Pradesh',
    price: 6800,
    unit: 'quintal',
    quantity: 500,
    qualityGrade: 'B+',
    harvestDate: '2026-10-10',
    images: ['https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=400&auto=format&fit=crop'],
    organic: false,
    verified: true,
    rating: 4.2,
    reviews: 12,
    description: 'Medium staple cotton from Guntur region. Good micronaire value, clean picking.',
    category: 'Fibre',
  },
  {
    id: '4',
    name: 'Turmeric',
    farmer: 'Lakshmi Devi',
    farmerId: 'f004',
    phone: '+919988776655',
    upiId: 'lakshmi.turmeric@okaxis',
    location: 'Nizamabad, Telangana',
    state: 'Telangana',
    price: 120,
    unit: 'kg',
    quantity: 800,
    qualityGrade: 'A+',
    harvestDate: '2026-09-01',
    images: ['https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=400&auto=format&fit=crop'],
    organic: true,
    verified: true,
    rating: 4.9,
    reviews: 56,
    description: 'Premium Nizamabad turmeric with high curcumin content. Certified organic, export quality.',
    category: 'Spices',
  },
  {
    id: '5',
    name: 'Red Chillies',
    farmer: 'Ramaiah Goud',
    farmerId: 'f005',
    phone: '+919701234567',
    upiId: 'ramaiah.goud@ybl',
    location: 'Khammam, Telangana',
    state: 'Telangana',
    price: 85,
    unit: 'kg',
    quantity: 1200,
    qualityGrade: 'A',
    harvestDate: '2026-08-30',
    images: ['https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&auto=format&fit=crop'],
    organic: false,
    verified: false,
    rating: 4.3,
    reviews: 18,
    description: 'Teja variety red chillies. High capsaicin content, vibrant red color.',
    category: 'Spices',
  },
  {
    id: '6',
    name: 'Onions',
    farmer: 'Dinesh Sharma',
    farmerId: 'f006',
    phone: '+919823112233',
    upiId: 'dinesh.onions@paytm',
    location: 'Lasalgaon, Maharashtra',
    state: 'Maharashtra',
    price: 22,
    unit: 'kg',
    quantity: 10000,
    qualityGrade: 'A',
    harvestDate: '2026-08-20',
    images: ['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&auto=format&fit=crop'],
    organic: false,
    verified: true,
    rating: 4.6,
    reviews: 89,
    description: 'Red Nasik onions. Medium size, good shelf life, low moisture.',
    category: 'Vegetables',
  },
  {
    id: '7',
    name: 'Wheat',
    farmer: 'Harpal Singh',
    farmerId: 'f007',
    phone: '+919876543210',
    upiId: 'harpal.wheat@oksbi',
    location: 'Ludhiana, Punjab',
    state: 'Punjab',
    price: 2275,
    unit: 'quintal',
    quantity: 200,
    qualityGrade: 'A+',
    harvestDate: '2026-04-15',
    images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&auto=format&fit=crop'],
    organic: false,
    verified: true,
    rating: 4.7,
    reviews: 34,
    description: 'HD-2967 variety wheat from Punjab. High protein content, ideal for flour mills.',
    category: 'Grains',
  },
  {
    id: '8',
    name: 'Mangoes (Alphonso)',
    farmer: 'Priya Desai',
    farmerId: 'f008',
    phone: '+919819988776',
    upiId: 'priya.mango@okhdfcbank',
    location: 'Ratnagiri, Maharashtra',
    state: 'Maharashtra',
    price: 350,
    unit: 'kg',
    quantity: 300,
    qualityGrade: 'A+',
    harvestDate: '2026-05-10',
    images: ['https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&auto=format&fit=crop'],
    organic: true,
    verified: true,
    rating: 5.0,
    reviews: 112,
    description: 'GI-tagged Alphonso mangoes from Ratnagiri. Sweet, aromatic, export quality.',
    category: 'Fruits',
  },
];

export const MANDI_PRICES = [
  { crop: 'Wheat', price: 2275, change: 15, unit: '/quintal', market: 'Delhi', trend: 'up' },
  { crop: 'Rice', price: 2183, change: -8, unit: '/quintal', market: 'Mumbai', trend: 'down' },
  { crop: 'Cotton', price: 6850, change: 120, unit: '/quintal', market: 'Ahmedabad', trend: 'up' },
  { crop: 'Soybean', price: 4420, change: 45, unit: '/quintal', market: 'Indore', trend: 'up' },
  { crop: 'Maize', price: 1920, change: -20, unit: '/quintal', market: 'Hyderabad', trend: 'down' },
  { crop: 'Turmeric', price: 12500, change: 300, unit: '/quintal', market: 'Nizamabad', trend: 'up' },
  { crop: 'Chilli', price: 8500, change: -200, unit: '/quintal', market: 'Guntur', trend: 'down' },
  { crop: 'Onion', price: 2200, change: 80, unit: '/quintal', market: 'Nashik', trend: 'up' },
  { crop: 'Tomato', price: 1800, change: 100, unit: '/quintal', market: 'Bangalore', trend: 'up' },
  { crop: 'Potato', price: 1400, change: -50, unit: '/quintal', market: 'Agra', trend: 'down' },
];

export const CROP_CALENDAR = [
  {
    crop: 'Rice (Kharif)',
    season: 'Kharif',
    sowingStart: 'June', sowingEnd: 'July',
    harvestStart: 'October', harvestEnd: 'November',
    regions: ['Telangana', 'Andhra Pradesh', 'West Bengal', 'Odisha'],
    soilType: 'Clay loam, Loamy', water: 'High',
    profitability: 'Medium', demand: 'High', icon: '🌾',
  },
  {
    crop: 'Wheat',
    season: 'Rabi',
    sowingStart: 'October', sowingEnd: 'November',
    harvestStart: 'March', harvestEnd: 'April',
    regions: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Madhya Pradesh'],
    soilType: 'Loamy, Sandy loam', water: 'Medium',
    profitability: 'High', demand: 'High', icon: '🌿',
  },
  {
    crop: 'Cotton',
    season: 'Kharif',
    sowingStart: 'May', sowingEnd: 'June',
    harvestStart: 'October', harvestEnd: 'December',
    regions: ['Gujarat', 'Maharashtra', 'Telangana', 'Andhra Pradesh'],
    soilType: 'Black cotton soil', water: 'Medium',
    profitability: 'High', demand: 'Very High', icon: '☁️',
  },
  {
    crop: 'Turmeric',
    season: 'Kharif',
    sowingStart: 'June', sowingEnd: 'July',
    harvestStart: 'January', harvestEnd: 'March',
    regions: ['Telangana', 'Andhra Pradesh', 'Tamil Nadu', 'Karnataka'],
    soilType: 'Sandy loam, Loamy', water: 'Medium',
    profitability: 'Very High', demand: 'High', icon: '🌟',
  },
  {
    crop: 'Soybean',
    season: 'Kharif',
    sowingStart: 'June', sowingEnd: 'July',
    harvestStart: 'September', harvestEnd: 'October',
    regions: ['Madhya Pradesh', 'Maharashtra', 'Rajasthan'],
    soilType: 'Well-drained loamy', water: 'Low-Medium',
    profitability: 'High', demand: 'High', icon: '🫘',
  },
  {
    crop: 'Groundnut',
    season: 'Kharif/Rabi',
    sowingStart: 'June', sowingEnd: 'July',
    harvestStart: 'September', harvestEnd: 'November',
    regions: ['Gujarat', 'Andhra Pradesh', 'Tamil Nadu', 'Karnataka'],
    soilType: 'Sandy loam', water: 'Low',
    profitability: 'Medium-High', demand: 'Medium', icon: '🥜',
  },
];

export const LOAN_SCHEMES = [
  {
    id: '1',
    name: 'Kisan Credit Card (KCC)',
    provider: 'All Nationalized Banks',
    interestRate: '4% (after subsidy)',
    maxAmount: '3,00,000',
    eligibility: 'All farmers with cultivable land',
    documents: ['Aadhaar Card', 'Land Records (Patta/Khata)', 'Passport Photo', 'Bank Account Details'],
    link: 'https://www.nabard.org/content1.aspx?id=572',
    description: 'Short-term credit for crop cultivation, post-harvest expenses, and allied activities.',
    icon: '💳',
  },
  {
    id: '2',
    name: 'PM-KISAN (₹6000/year)',
    provider: 'Central Government',
    interestRate: 'N/A (Direct benefit)',
    maxAmount: '6,000/year',
    eligibility: 'Small & marginal farmers with < 2 hectares',
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account'],
    link: 'https://pmkisan.gov.in/',
    description: 'Direct income support of ₹6000/year in three equal installments.',
    icon: '🏛️',
  },
  {
    id: '3',
    name: 'PMFBY - Crop Insurance',
    provider: 'Ministry of Agriculture',
    interestRate: '2% premium (Kharif)',
    maxAmount: 'As per crop notified',
    eligibility: 'All farmers growing notified crops',
    documents: ['Aadhaar', 'Land Records', 'Bank Account', 'Crop Sowing Certificate'],
    link: 'https://pmfby.gov.in/',
    description: 'Comprehensive crop insurance against natural calamities, pests & diseases.',
    icon: '🛡️',
  },
  {
    id: '4',
    name: 'Agricultural Term Loan',
    provider: 'NABARD / Banks',
    interestRate: '7-9%',
    maxAmount: '10,00,000',
    eligibility: 'Farmers for capital investments',
    documents: ['Aadhaar', 'Land Records', 'Income Proof', 'Project Report'],
    link: 'https://www.nabard.org/',
    description: 'Long-term loans for farm equipment, irrigation, storage, and infrastructure.',
    icon: '🚜',
  },
];

export const DISEASES = [
  {
    id: '1',
    name: 'Rice Blast',
    crop: 'Rice',
    severity: 'High',
    confidence: 94,
    symptoms: 'Diamond-shaped lesions on leaves, white to gray center with brown border',
    organicTreatment: 'Neem oil spray (5ml/L water), Trichoderma viride application',
    chemicalTreatment: 'Tricyclazole 75% WP @ 0.6g/L or Carbendazim 50% WP @ 1g/L',
    dosage: 'Spray twice at 10-day interval',
    prevention: 'Use resistant varieties, avoid excess nitrogen',
  },
  {
    id: '2',
    name: 'Tomato Leaf Curl Virus',
    crop: 'Tomato',
    severity: 'Medium',
    confidence: 89,
    symptoms: 'Leaf curling upwards, yellowing, stunted growth, reduced fruit set',
    organicTreatment: 'Yellow sticky traps for whitefly control, Neem-based spray',
    chemicalTreatment: 'Imidacloprid 17.8% SL @ 0.5ml/L for whitefly control',
    dosage: 'Apply every 7 days for 3 weeks',
    prevention: 'Use virus-free seedlings, control whitefly population',
  },
  {
    id: '3',
    name: 'Powdery Mildew',
    crop: 'Wheat',
    severity: 'Medium',
    confidence: 91,
    symptoms: 'White powdery spots on leaves and stems, yellowing of affected tissue',
    organicTreatment: 'Baking soda solution (1 tsp/L water) or neem oil spray',
    chemicalTreatment: 'Propiconazole 25% EC @ 0.1% or Hexaconazole 5% EC @ 0.1%',
    dosage: 'Two sprays at 15-day intervals',
    prevention: 'Crop rotation, avoid dense planting, use resistant varieties',
  },
];

export const FORUM_POSTS = [
  {
    id: '1',
    author: 'Rajesh Kumar',
    avatar: '👨‍🌾',
    title: 'Best variety of rice for Kharif 2026 in Telangana?',
    content: 'I want to try a new high-yield variety this season. Any recommendations for water-efficient rice that gives good market price?',
    replies: 14,
    likes: 32,
    tags: ['Rice', 'Kharif', 'Telangana'],
    time: '2 hours ago',
    category: 'Crop Advice',
  },
  {
    id: '2',
    author: 'Suresh Patil',
    avatar: '🧑‍🌾',
    title: 'My experience with Kisan Credit Card application',
    content: 'Here is a step-by-step guide on how I got my KCC approved in just 2 weeks without any broker...',
    replies: 28,
    likes: 67,
    tags: ['KCC', 'Loan', 'Finance'],
    time: '5 hours ago',
    category: 'Finance Tips',
  },
  {
    id: '3',
    author: 'Lakshmi Devi',
    avatar: '👩‍🌾',
    title: 'Organic turmeric farming — doubled my income!',
    content: 'After switching to organic methods 2 years ago, I get 40% premium price in the market. Let me share my journey...',
    replies: 45,
    likes: 120,
    tags: ['Organic', 'Turmeric', 'Success Story'],
    time: '1 day ago',
    category: 'Success Story',
  },
  {
    id: '4',
    author: 'Manoj Yadav',
    avatar: '👨‍🌾',
    title: 'Cotton pest attack — what to do urgently?',
    content: 'My cotton field has white flies attacking badly. Already tried neem oil but not working. Need urgent help!',
    replies: 22,
    likes: 15,
    tags: ['Cotton', 'Pest', 'Urgent'],
    time: '3 hours ago',
    category: 'Pest & Disease',
  },
];

export const GOVT_SCHEMES = [
  { title: 'PM-KISAN 20th Installment Released — Check Your Account', date: '2026-08-01', category: 'Finance', urgent: true },
  { title: 'PMFBY Enrollment Deadline: Aug 31 for Kharif Crops', date: '2026-08-15', category: 'Insurance', urgent: true },
  { title: 'Free Soil Health Cards — Register at Your Local Agriculture Office', date: '2026-08-10', category: 'Services', urgent: false },
  { title: 'Drone Subsidy for Farmers — 40% Grant Available', date: '2026-08-05', category: 'Technology', urgent: false },
  { title: 'Organic Farming Mission — ₹50,000 Subsidy per Farmer', date: '2026-07-28', category: 'Organic', urgent: false },
  { title: 'Natural Farming Training Camp — Register Now', date: '2026-07-20', category: 'Training', urgent: false },
];

export const CHATBOT_RESPONSES: Record<string, string> = {
  'rice': 'For Kharif rice in Telangana/AP, sow between June-July. Use varieties like BPT 5204 or MTU 1010. Ensure 5cm water standing. Expected yield: 5-6 tons/hectare.',
  'wheat': 'Wheat is a Rabi crop. Sow between Oct-Nov in well-drained loamy soil. Water 4-5 times. Best varieties: HD-2967, PBW-343. Expected yield: 4-5 tons/hectare.',
  'cotton': 'Cotton grows well in black soil. Sow May-June. Use drip irrigation. Watch for bollworm and whitefly. Current mandi price: ₹6,850/quintal.',
  'fertilizer': 'For most crops: Apply 120:60:40 kg NPK per hectare as basal dose. Top-dress with urea at 30 and 60 days after sowing.',
  'loan': 'Kisan Credit Card offers crop loans at 4% interest (after 3% government subsidy). Visit your nearest nationalized bank with Aadhaar, land records and passport photo.',
  'disease': 'Upload a clear photo of the affected leaf or plant to our Disease Detection tool. I can help identify the problem and suggest treatment. Common treatments: Neem oil for organic, Tricyclazole for fungal diseases.',
  'weather': 'Current season: Kharif 2026. Southwest monsoon is active. Expect rainfall of 100-150mm in the next week. Good conditions for rice and cotton.',
  'price': 'Today\'s key mandi prices: Wheat ₹2,275/q, Rice ₹2,183/q, Cotton ₹6,850/q, Turmeric ₹12,500/q, Onion ₹2,200/q. Prices updated daily.',
  'sell': 'To sell on AGRONOMY 360: 1) Create a farmer account, 2) Click "List Your Crop", 3) Add photos, price, quantity, 4) Buyers will contact you directly. Zero commission!',
  'organic': 'Organic farming premium: Turmeric gets 40% higher price, Rice gets 25% more. Certification through PGS-India is free for small farmers. Contact your local Krishi Vigyan Kendra.',
  'default': 'I\'m your AI farming assistant! Ask me about: crop recommendations, market prices, disease treatment, government schemes, loans, or selling on this platform. Type your question in any language!',
};
